# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evap-Sim-005.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 341, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Model_Resolution = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Resolution.setFont(font)
        self.label_Model_Resolution.setObjectName("label_Model_Resolution")
        self.gridLayout.addWidget(self.label_Model_Resolution, 0, 0, 1, 1)
        self.label_Grid_Space = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Grid_Space.setFont(font)
        self.label_Grid_Space.setObjectName("label_Grid_Space")
        self.gridLayout.addWidget(self.label_Grid_Space, 3, 0, 1, 1)
        self.lineEdit_Model_Resolution = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Model_Resolution.setObjectName(
            "lineEdit_Model_Resolution")
        self.gridLayout.addWidget(self.lineEdit_Model_Resolution, 0, 1, 1, 1)
        self.label_Evaporation_Rate = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Rate.setFont(font)
        self.label_Evaporation_Rate.setObjectName("label_Evaporation_Rate")
        self.gridLayout.addWidget(self.label_Evaporation_Rate, 1, 0, 1, 1)
        self.label_Raycast_Length = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Raycast_Length.setFont(font)
        self.label_Raycast_Length.setObjectName("label_Raycast_Length")
        self.gridLayout.addWidget(self.label_Raycast_Length, 4, 0, 1, 1)
        self.label_Evaporation_Time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Time.setFont(font)
        self.label_Evaporation_Time.setObjectName("label_Evaporation_Time")
        self.gridLayout.addWidget(self.label_Evaporation_Time, 2, 0, 1, 1)
        self.label_Model_Resolution_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Resolution_Unit.setFont(font)
        self.label_Model_Resolution_Unit.setObjectName(
            "label_Model_Resolution_Unit")
        self.gridLayout.addWidget(self.label_Model_Resolution_Unit, 0, 2, 1, 1)
        self.label_Model_Limit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Limit.setFont(font)
        self.label_Model_Limit.setObjectName("label_Model_Limit")
        self.gridLayout.addWidget(self.label_Model_Limit, 5, 0, 1, 1)
        self.lineEdit_Evaporation_Rate = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Evaporation_Rate.setObjectName(
            "lineEdit_Evaporation_Rate")
        self.gridLayout.addWidget(self.lineEdit_Evaporation_Rate, 1, 1, 1, 1)
        self.lineEdit_Evaporation_Time = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Evaporation_Time.setObjectName(
            "lineEdit_Evaporation_Time")
        self.gridLayout.addWidget(self.lineEdit_Evaporation_Time, 2, 1, 1, 1)
        self.lineEdit_Grid_Space = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Grid_Space.setObjectName("lineEdit_Grid_Space")
        self.gridLayout.addWidget(self.lineEdit_Grid_Space, 3, 1, 1, 1)
        self.lineEdit_Raycast_Length = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Raycast_Length.setObjectName("lineEdit_Raycast_Length")
        self.gridLayout.addWidget(self.lineEdit_Raycast_Length, 4, 1, 1, 1)
        self.lineEdit_Model_Limit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Model_Limit.setObjectName("lineEdit_Model_Limit")
        self.gridLayout.addWidget(self.lineEdit_Model_Limit, 5, 1, 1, 1)
        self.label_Evaporation_Rate_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Rate_Unit.setFont(font)
        self.label_Evaporation_Rate_Unit.setObjectName(
            "label_Evaporation_Rate_Unit")
        self.gridLayout.addWidget(self.label_Evaporation_Rate_Unit, 1, 2, 1, 1)
        self.label_Evaporation_Time_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Time_Unit.setFont(font)
        self.label_Evaporation_Time_Unit.setObjectName(
            "label_Evaporation_Time_Unit")
        self.gridLayout.addWidget(self.label_Evaporation_Time_Unit, 2, 2, 1, 1)
        self.label_Grid_Space_Unit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Grid_Space_Unit.setFont(font)
        self.label_Grid_Space_Unit.setObjectName("label_Grid_Space_Unit")
        self.gridLayout.addWidget(self.label_Grid_Space_Unit, 3, 2, 1, 1)
        self.label_Raycast_Length_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Raycast_Length_Unit.setFont(font)
        self.label_Raycast_Length_Unit.setObjectName(
            "label_Raycast_Length_Unit")
        self.gridLayout.addWidget(self.label_Raycast_Length_Unit, 4, 2, 1, 1)
        self.label_Model_Limit_Unit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Limit_Unit.setFont(font)
        self.label_Model_Limit_Unit.setObjectName("label_Model_Limit_Unit")
        self.gridLayout.addWidget(self.label_Model_Limit_Unit, 5, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 149, 95))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Left = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.verticalLayout_Left.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Left.setObjectName("verticalLayout_Left")
        self.pushButton_Load_Model = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Load_Model.setFont(font)
        self.pushButton_Load_Model.setObjectName("pushButton_Load_Model")
        self.verticalLayout_Left.addWidget(self.pushButton_Load_Model)
        self.pushButton_Load_Evap_Profile = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Load_Evap_Profile.setFont(font)
        self.pushButton_Load_Evap_Profile.setObjectName(
            "pushButton_Load_Evap_Profile")
        self.verticalLayout_Left.addWidget(self.pushButton_Load_Evap_Profile)
        self.pushButton_Save_Evap_Profile = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Save_Evap_Profile.setFont(font)
        self.pushButton_Save_Evap_Profile.setObjectName(
            "pushButton_Save_Evap_Profile")
        self.verticalLayout_Left.addWidget(self.pushButton_Save_Evap_Profile)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(
            QtCore.QRect(240, 200, 110, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Right = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.verticalLayout_Right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Right.setObjectName("verticalLayout_Right")
        self.pushButton_Abort_Run = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Abort_Run.setFont(font)
        self.pushButton_Abort_Run.setObjectName("pushButton_Abort_Run")
        self.verticalLayout_Right.addWidget(self.pushButton_Abort_Run)
        self.pushButton_Clear_Run = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Clear_Run.setFont(font)
        self.pushButton_Clear_Run.setObjectName("pushButton_Clear_Run")
        self.verticalLayout_Right.addWidget(self.pushButton_Clear_Run)
        self.pushButton_Reset_Graph = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Reset_Graph.setFont(font)
        self.pushButton_Reset_Graph.setObjectName("pushButton_Reset_Graph")
        self.verticalLayout_Right.addWidget(self.pushButton_Reset_Graph)
        self.tabWidget_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Main.setGeometry(QtCore.QRect(360, 10, 661, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_Main.setFont(font)
        self.tabWidget_Main.setObjectName("tabWidget_Main")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_1.setFont(font)
        self.tab_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_1.setMouseTracking(False)
        self.tab_1.setAcceptDrops(False)
        self.tab_1.setAutoFillBackground(False)
        self.tab_1.setObjectName("tab_1")
        self.graphicsView_Model = QtWidgets.QGraphicsView(self.tab_1)
        self.graphicsView_Model.setGeometry(QtCore.QRect(-1, -1, 660, 660))
        self.graphicsView_Model.setObjectName("graphicsView_Model")
        self.tabWidget_Main.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_Evap_Profile_Top = QtWidgets.QGraphicsView(
            self.tab_2)
        self.graphicsView_Evap_Profile_Top.setGeometry(
            QtCore.QRect(-1, -1, 660, 330))
        self.graphicsView_Evap_Profile_Top.setObjectName(
            "graphicsView_Evap_Profile_Top")
        self.graphicsView_Evap_Profile_Bottom = QtWidgets.QGraphicsView(
            self.tab_2)
        self.graphicsView_Evap_Profile_Bottom.setGeometry(
            QtCore.QRect(-1, 329, 660, 330))
        self.graphicsView_Evap_Profile_Bottom.setObjectName(
            "graphicsView_Evap_Profile_Bottom")
        self.tabWidget_Main.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_Log = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_Log.setGeometry(QtCore.QRect(-1, -1, 660, 661))
        self.textBrowser_Log.setObjectName("textBrowser_Log")
        self.tabWidget_Main.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_InfoGPU = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_InfoGPU.setGeometry(QtCore.QRect(10, 10, 641, 181))
        self.textBrowser_InfoGPU.setStatusTip("")
        self.textBrowser_InfoGPU.setWhatsThis("")
        self.textBrowser_InfoGPU.setAccessibleName("")
        self.textBrowser_InfoGPU.setAccessibleDescription("")
        self.textBrowser_InfoGPU.setDocumentTitle("")
        self.textBrowser_InfoGPU.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Peak: </span><span style=\" font-style:italic;\">if Pi[i - 1] != 0 and Pi[i] == 0 and Pi[i + 1] != 0:</span></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    The ith point is averaged against its neighbors.</p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Divet: </span><span style=\" font-style:italic;\">if Pi[i - 1] == 0 and Pi[i] != 0 and Pi[i + 1] == 0:</span></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    The ith point is averaged against its neighbors.</p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Corners: </span><span style=\" font-style:italic;\">Pi[i - 1] != 0 and Pi[i + 1] == 0: </span><span style=\" font-weight:600; font-style:italic;\">or</span></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">    Pi[i + 1] != 0 and Pi[i - 1] == 0:</span></p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">    </span>The ith point is kept along with the adjusted ith point</p></body></html>")
        self.textBrowser_InfoGPU.setPlaceholderText("")
        self.textBrowser_InfoGPU.setObjectName("textBrowser_InfoGPU")
        self.label_GPU_Corrections = QtWidgets.QLabel(self.tab)
        self.label_GPU_Corrections.setGeometry(QtCore.QRect(20, 200, 141, 16))
        self.label_GPU_Corrections.setObjectName("label_GPU_Corrections")
        self.label_CPU_Corrections = QtWidgets.QLabel(self.tab)
        self.label_CPU_Corrections.setGeometry(QtCore.QRect(10, 320, 141, 16))
        self.label_CPU_Corrections.setObjectName("label_CPU_Corrections")
        self.textBrowser_InfoCPU = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_InfoCPU.setGeometry(QtCore.QRect(10, 260, 641, 51))
        self.textBrowser_InfoCPU.setObjectName("textBrowser_InfoCPU")
        self.checkBox_divet = QtWidgets.QCheckBox(self.tab)
        self.checkBox_divet.setGeometry(QtCore.QRect(170, 200, 171, 21))
        self.checkBox_divet.setChecked(True)
        self.checkBox_divet.setObjectName("checkBox_divet")
        self.checkBox_peaks = QtWidgets.QCheckBox(self.tab)
        self.checkBox_peaks.setGeometry(QtCore.QRect(170, 230, 171, 21))
        self.checkBox_peaks.setObjectName("checkBox_peaks")
        self.checkBox_modelRes = QtWidgets.QCheckBox(self.tab)
        self.checkBox_modelRes.setGeometry(QtCore.QRect(160, 320, 221, 21))
        self.checkBox_modelRes.setChecked(True)
        self.checkBox_modelRes.setObjectName("checkBox_modelRes")
        self.checkBox_corners = QtWidgets.QCheckBox(self.tab)
        self.checkBox_corners.setGeometry(QtCore.QRect(370, 230, 161, 21))
        self.checkBox_corners.setChecked(True)
        self.checkBox_corners.setObjectName("checkBox_corners")
        self.checkBox_grid = QtWidgets.QCheckBox(self.tab)
        self.checkBox_grid.setGeometry(QtCore.QRect(370, 200, 171, 21))
        self.checkBox_grid.setChecked(True)
        self.checkBox_grid.setObjectName("checkBox_grid")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 360, 491, 153))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_GPUfunc = QtWidgets.QGridLayout(
            self.gridLayoutWidget_2)
        self.gridLayout_GPUfunc.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_GPUfunc.setObjectName("gridLayout_GPUfunc")
        self.label_epsGrid = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsGrid.setObjectName("label_epsGrid")
        self.gridLayout_GPUfunc.addWidget(self.label_epsGrid, 2, 0, 1, 1)
        self.lineEdit_decGrid = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decGrid.setObjectName("lineEdit_decGrid")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decGrid, 2, 2, 1, 1)
        self.lineEdit_epsGrid = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsGrid.setObjectName("lineEdit_epsGrid")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsGrid, 2, 1, 1, 1)
        self.lineEdit_epsIntersect = QtWidgets.QLineEdit(
            self.gridLayoutWidget_2)
        self.lineEdit_epsIntersect.setObjectName("lineEdit_epsIntersect")
        self.gridLayout_GPUfunc.addWidget(
            self.lineEdit_epsIntersect, 1, 1, 1, 1)
        self.lineEdit_decIntersect = QtWidgets.QLineEdit(
            self.gridLayoutWidget_2)
        self.lineEdit_decIntersect.setObjectName("lineEdit_decIntersect")
        self.gridLayout_GPUfunc.addWidget(
            self.lineEdit_decIntersect, 1, 2, 1, 1)
        self.label_epsIntersect = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsIntersect.setObjectName("label_epsIntersect")
        self.gridLayout_GPUfunc.addWidget(self.label_epsIntersect, 1, 0, 1, 1)
        self.label_Rounding = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Rounding.setObjectName("label_Rounding")
        self.gridLayout_GPUfunc.addWidget(self.label_Rounding, 0, 2, 1, 1)
        self.label_eps = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_eps.setObjectName("label_eps")
        self.gridLayout_GPUfunc.addWidget(self.label_eps, 0, 1, 1, 1)
        self.label_epsModel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsModel.setObjectName("label_epsModel")
        self.gridLayout_GPUfunc.addWidget(self.label_epsModel, 3, 0, 1, 1)
        self.label_epsMerge = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsMerge.setObjectName("label_epsMerge")
        self.gridLayout_GPUfunc.addWidget(self.label_epsMerge, 4, 0, 1, 1)
        self.lineEdit_epsModel = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsModel.setObjectName("lineEdit_epsModel")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsModel, 3, 1, 1, 1)
        self.lineEdit_decModel = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decModel.setObjectName("lineEdit_decModel")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decModel, 3, 2, 1, 1)
        self.lineEdit_epsMerge = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsMerge.setObjectName("lineEdit_epsMerge")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsMerge, 4, 1, 1, 1)
        self.lineEdit_decMerge = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decMerge.setObjectName("lineEdit_decMerge")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decMerge, 4, 2, 1, 1)
        self.label_GPUTolerance = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_GPUTolerance.setObjectName("label_GPUTolerance")
        self.gridLayout_GPUfunc.addWidget(self.label_GPUTolerance, 0, 0, 1, 1)
        self.tabWidget_Main.addTab(self.tab, "")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(
            QtCore.QRect(10, 310, 341, 451))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_Info = QtWidgets.QTextBrowser(
            self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.textBrowser_Info.setFont(font)
        self.textBrowser_Info.setObjectName("textBrowser_Info")
        self.verticalLayout_3.addWidget(self.textBrowser_Info)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(360, 710, 231, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(600, 710, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setAutoRepeatInterval(100)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Pause = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Pause.setFont(font)
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.horizontalLayout.addWidget(self.pushButton_Pause)
        self.pushButton_Quit = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Quit.setFont(font)
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.horizontalLayout.addWidget(self.pushButton_Quit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 20))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(
            self.lineEdit_Model_Resolution, self.lineEdit_Evaporation_Rate)
        MainWindow.setTabOrder(
            self.lineEdit_Evaporation_Rate, self.lineEdit_Evaporation_Time)
        MainWindow.setTabOrder(
            self.lineEdit_Evaporation_Time, self.lineEdit_Grid_Space)
        MainWindow.setTabOrder(self.lineEdit_Grid_Space,
                               self.lineEdit_Raycast_Length)
        MainWindow.setTabOrder(
            self.lineEdit_Raycast_Length, self.lineEdit_Model_Limit)
        MainWindow.setTabOrder(self.lineEdit_Model_Limit,
                               self.pushButton_Load_Model)
        MainWindow.setTabOrder(self.pushButton_Load_Model,
                               self.pushButton_Load_Evap_Profile)
        MainWindow.setTabOrder(
            self.pushButton_Load_Evap_Profile, self.pushButton_Save_Evap_Profile)
        MainWindow.setTabOrder(
            self.pushButton_Save_Evap_Profile, self.pushButton_Abort_Run)
        MainWindow.setTabOrder(self.pushButton_Abort_Run,
                               self.pushButton_Clear_Run)
        MainWindow.setTabOrder(self.pushButton_Clear_Run,
                               self.pushButton_Reset_Graph)
        MainWindow.setTabOrder(
            self.pushButton_Reset_Graph, self.tabWidget_Main)
        MainWindow.setTabOrder(self.tabWidget_Main, self.graphicsView_Model)
        MainWindow.setTabOrder(self.graphicsView_Model,
                               self.graphicsView_Evap_Profile_Top)
        MainWindow.setTabOrder(
            self.graphicsView_Evap_Profile_Top, self.graphicsView_Evap_Profile_Bottom)
        MainWindow.setTabOrder(
            self.graphicsView_Evap_Profile_Bottom, self.textBrowser_Log)
        MainWindow.setTabOrder(self.textBrowser_Log, self.textBrowser_Info)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Physical Vapor Depostion Simulator"))
        self.label_Model_Resolution.setText(
            _translate("MainWindow", "Model Resolution"))
        self.label_Grid_Space.setText(_translate("MainWindow", "Grid Space"))
        self.label_Evaporation_Rate.setText(
            _translate("MainWindow", "Evaporation Rate"))
        self.label_Raycast_Length.setText(
            _translate("MainWindow", "Raycast Length"))
        self.label_Evaporation_Time.setText(
            _translate("MainWindow", "Evaporation Time"))
        self.label_Model_Resolution_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Model_Limit.setText(_translate("MainWindow", "Model Limit"))
        self.label_Evaporation_Rate_Unit.setText(
            _translate("MainWindow", "Å/s"))
        self.label_Evaporation_Time_Unit.setText(_translate("MainWindow", "s"))
        self.label_Grid_Space_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Raycast_Length_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Model_Limit_Unit.setText(_translate("MainWindow", "Pts"))
        self.pushButton_Load_Model.setText(
            _translate("MainWindow", "Load Model"))
        self.pushButton_Load_Evap_Profile.setText(
            _translate("MainWindow", "Load Evap Profile"))
        self.pushButton_Save_Evap_Profile.setText(
            _translate("MainWindow", "Save Evap Model"))
        self.pushButton_Abort_Run.setText(
            _translate("MainWindow", "Abort Run"))
        self.pushButton_Clear_Run.setText(
            _translate("MainWindow", "Clear Run"))
        self.pushButton_Reset_Graph.setText(
            _translate("MainWindow", "Reset Graph"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_1), _translate("MainWindow", "Model"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_2), _translate("MainWindow", "Evap Profile"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_3), _translate("MainWindow", "Log"))
        self.label_GPU_Corrections.setText(
            _translate("MainWindow", "GPU Corrections:"))
        self.label_CPU_Corrections.setText(
            _translate("MainWindow", "CPU Corrections:"))
        self.textBrowser_InfoCPU.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Model Resolution: </span>The distance between points is checked. If a point is less than the minimum distance allowed it is dropped from the model.</p></body></html>"))
        self.checkBox_divet.setText(_translate(
            "MainWindow", "Average out divets"))
        self.checkBox_peaks.setText(_translate(
            "MainWindow", "Average out peaks"))
        self.checkBox_modelRes.setText(_translate(
            "MainWindow", "Enforce Model Resolution"))
        self.checkBox_corners.setText(
            _translate("MainWindow", "Preserve corners"))
        self.checkBox_grid.setText(_translate(
            "MainWindow", "Enfore Grid Space"))
        self.label_epsGrid.setText(_translate("MainWindow", "Grid"))
        self.lineEdit_decGrid.setText(_translate("MainWindow", "10"))
        self.lineEdit_epsGrid.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_epsIntersect.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_decIntersect.setText(_translate("MainWindow", "10"))
        self.label_epsIntersect.setText(
            _translate("MainWindow", "Intersection"))
        self.label_Rounding.setText(_translate(
            "MainWindow", "Rounding Accuracy"))
        self.label_eps.setText(_translate(
            "MainWindow", "Computer Determined Zero"))
        self.label_epsModel.setText(_translate("MainWindow", "Model"))
        self.label_epsMerge.setText(_translate("MainWindow", "Merge"))
        self.lineEdit_epsModel.setText(_translate("MainWindow", "1e-10"))
        self.lineEdit_decModel.setText(_translate("MainWindow", "10"))
        self.lineEdit_epsMerge.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_decMerge.setText(_translate("MainWindow", "10"))
        self.label_GPUTolerance.setText(_translate("MainWindow", "GPU func:"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab), _translate("MainWindow", "Settings"))
        self.textBrowser_Info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Model Resolution: </span>Density of the raycasts on the model.</p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Evaporation Rate: </span>Material deposition rate</p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Grid Space:</span> Vertice resolution. Model attempts to merge points within a distance smaller than this. Helps reduce artifacts from forming.</p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Raycast Length: </span>Size of ray extended from each point in model. Too large a ray can produce floating point errors. Too small can miss intesections against model.</p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Model Limit: </span>Maximum amount of points allowed in model. When this is hit the model is reduced to set model resolution.</p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Helpful for decluttering curves with thousands of points.</p></body></html>"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_Quit.setText(_translate("MainWindow", "Quit"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
