# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evap-Sim-006.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 10, 341, 182))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Model_Resolution = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Resolution.setFont(font)
        self.label_Model_Resolution.setObjectName("label_Model_Resolution")
        self.gridLayout.addWidget(self.label_Model_Resolution, 0, 0, 1, 1)
        self.label_Grid_Space = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Grid_Space.setFont(font)
        self.label_Grid_Space.setObjectName("label_Grid_Space")
        self.gridLayout.addWidget(self.label_Grid_Space, 3, 0, 1, 1)
        self.lineEdit_Model_Resolution = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Model_Resolution.setObjectName(
            "lineEdit_Model_Resolution")
        self.gridLayout.addWidget(self.lineEdit_Model_Resolution, 0, 1, 1, 1)
        self.label_Evaporation_Rate = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Rate.setFont(font)
        self.label_Evaporation_Rate.setObjectName("label_Evaporation_Rate")
        self.gridLayout.addWidget(self.label_Evaporation_Rate, 1, 0, 1, 1)
        self.label_Raycast_Length = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Raycast_Length.setFont(font)
        self.label_Raycast_Length.setObjectName("label_Raycast_Length")
        self.gridLayout.addWidget(self.label_Raycast_Length, 4, 0, 1, 1)
        self.label_Evaporation_Time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Time.setFont(font)
        self.label_Evaporation_Time.setObjectName("label_Evaporation_Time")
        self.gridLayout.addWidget(self.label_Evaporation_Time, 2, 0, 1, 1)
        self.label_Model_Resolution_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Resolution_Unit.setFont(font)
        self.label_Model_Resolution_Unit.setObjectName(
            "label_Model_Resolution_Unit")
        self.gridLayout.addWidget(self.label_Model_Resolution_Unit, 0, 2, 1, 1)
        self.label_Model_Limit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Limit.setFont(font)
        self.label_Model_Limit.setObjectName("label_Model_Limit")
        self.gridLayout.addWidget(self.label_Model_Limit, 5, 0, 1, 1)
        self.lineEdit_Evaporation_Rate = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Evaporation_Rate.setObjectName(
            "lineEdit_Evaporation_Rate")
        self.gridLayout.addWidget(self.lineEdit_Evaporation_Rate, 1, 1, 1, 1)
        self.lineEdit_Evaporation_Time = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Evaporation_Time.setObjectName(
            "lineEdit_Evaporation_Time")
        self.gridLayout.addWidget(self.lineEdit_Evaporation_Time, 2, 1, 1, 1)
        self.lineEdit_Grid_Space = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Grid_Space.setObjectName("lineEdit_Grid_Space")
        self.gridLayout.addWidget(self.lineEdit_Grid_Space, 3, 1, 1, 1)
        self.lineEdit_Raycast_Length = QtWidgets.QLineEdit(
            self.gridLayoutWidget)
        self.lineEdit_Raycast_Length.setObjectName("lineEdit_Raycast_Length")
        self.gridLayout.addWidget(self.lineEdit_Raycast_Length, 4, 1, 1, 1)
        self.lineEdit_Model_Limit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Model_Limit.setObjectName("lineEdit_Model_Limit")
        self.gridLayout.addWidget(self.lineEdit_Model_Limit, 5, 1, 1, 1)
        self.label_Evaporation_Rate_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Rate_Unit.setFont(font)
        self.label_Evaporation_Rate_Unit.setObjectName(
            "label_Evaporation_Rate_Unit")
        self.gridLayout.addWidget(self.label_Evaporation_Rate_Unit, 1, 2, 1, 1)
        self.label_Evaporation_Time_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Evaporation_Time_Unit.setFont(font)
        self.label_Evaporation_Time_Unit.setObjectName(
            "label_Evaporation_Time_Unit")
        self.gridLayout.addWidget(self.label_Evaporation_Time_Unit, 2, 2, 1, 1)
        self.label_Grid_Space_Unit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Grid_Space_Unit.setFont(font)
        self.label_Grid_Space_Unit.setObjectName("label_Grid_Space_Unit")
        self.gridLayout.addWidget(self.label_Grid_Space_Unit, 3, 2, 1, 1)
        self.label_Raycast_Length_Unit = QtWidgets.QLabel(
            self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Raycast_Length_Unit.setFont(font)
        self.label_Raycast_Length_Unit.setObjectName(
            "label_Raycast_Length_Unit")
        self.gridLayout.addWidget(self.label_Raycast_Length_Unit, 4, 2, 1, 1)
        self.label_Model_Limit_Unit = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Model_Limit_Unit.setFont(font)
        self.label_Model_Limit_Unit.setObjectName("label_Model_Limit_Unit")
        self.gridLayout.addWidget(self.label_Model_Limit_Unit, 5, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 200, 149, 144))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Left = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.verticalLayout_Left.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Left.setObjectName("verticalLayout_Left")
        self.pushButton_Load_Model = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Load_Model.setFont(font)
        self.pushButton_Load_Model.setObjectName("pushButton_Load_Model")
        self.verticalLayout_Left.addWidget(self.pushButton_Load_Model)
        self.pushButton_Load_Evap_Profile = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Load_Evap_Profile.setFont(font)
        self.pushButton_Load_Evap_Profile.setObjectName(
            "pushButton_Load_Evap_Profile")
        self.verticalLayout_Left.addWidget(self.pushButton_Load_Evap_Profile)
        self.pushButton_load_settings = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_load_settings.setFont(font)
        self.pushButton_load_settings.setObjectName("pushButton_load_settings")
        self.verticalLayout_Left.addWidget(self.pushButton_load_settings)
        self.pushButton_Save_Evap_Profile = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Save_Evap_Profile.setFont(font)
        self.pushButton_Save_Evap_Profile.setObjectName(
            "pushButton_Save_Evap_Profile")
        self.verticalLayout_Left.addWidget(self.pushButton_Save_Evap_Profile)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(
            QtCore.QRect(240, 200, 110, 107))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Right = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.verticalLayout_Right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Right.setObjectName("verticalLayout_Right")
        self.pushButton_Abort_Run = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Abort_Run.setFont(font)
        self.pushButton_Abort_Run.setObjectName("pushButton_Abort_Run")
        self.verticalLayout_Right.addWidget(self.pushButton_Abort_Run)
        self.pushButton_Clear_Run = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Clear_Run.setFont(font)
        self.pushButton_Clear_Run.setObjectName("pushButton_Clear_Run")
        self.verticalLayout_Right.addWidget(self.pushButton_Clear_Run)
        self.pushButton_Reset_Graph = QtWidgets.QPushButton(
            self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Reset_Graph.setFont(font)
        self.pushButton_Reset_Graph.setObjectName("pushButton_Reset_Graph")
        self.verticalLayout_Right.addWidget(self.pushButton_Reset_Graph)
        self.tabWidget_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Main.setGeometry(QtCore.QRect(360, 10, 661, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_Main.setFont(font)
        self.tabWidget_Main.setObjectName("tabWidget_Main")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_1.setFont(font)
        self.tab_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_1.setMouseTracking(False)
        self.tab_1.setAcceptDrops(False)
        self.tab_1.setAutoFillBackground(False)
        self.tab_1.setObjectName("tab_1")
        self.graphicsView_Model = QtWidgets.QGraphicsView(self.tab_1)
        self.graphicsView_Model.setGeometry(QtCore.QRect(-1, -1, 660, 660))
        self.graphicsView_Model.setObjectName("graphicsView_Model")
        self.tabWidget_Main.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_Evap_Profile_Top = QtWidgets.QGraphicsView(
            self.tab_2)
        self.graphicsView_Evap_Profile_Top.setGeometry(
            QtCore.QRect(-1, -1, 660, 330))
        self.graphicsView_Evap_Profile_Top.setObjectName(
            "graphicsView_Evap_Profile_Top")
        self.graphicsView_Evap_Profile_Bottom = QtWidgets.QGraphicsView(
            self.tab_2)
        self.graphicsView_Evap_Profile_Bottom.setGeometry(
            QtCore.QRect(-1, 329, 660, 330))
        self.graphicsView_Evap_Profile_Bottom.setObjectName(
            "graphicsView_Evap_Profile_Bottom")
        self.tabWidget_Main.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_Log = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_Log.setGeometry(QtCore.QRect(-1, -1, 660, 661))
        self.textBrowser_Log.setObjectName("textBrowser_Log")
        self.tabWidget_Main.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_GPU_Corrections = QtWidgets.QLabel(self.tab)
        self.label_GPU_Corrections.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_GPU_Corrections.setObjectName("label_GPU_Corrections")
        self.label_CPU_Corrections = QtWidgets.QLabel(self.tab)
        self.label_CPU_Corrections.setGeometry(QtCore.QRect(10, 70, 141, 16))
        self.label_CPU_Corrections.setObjectName("label_CPU_Corrections")
        self.checkBox_divet = QtWidgets.QCheckBox(self.tab)
        self.checkBox_divet.setGeometry(QtCore.QRect(160, 10, 171, 21))
        self.checkBox_divet.setChecked(True)
        self.checkBox_divet.setObjectName("checkBox_divet")
        self.checkBox_peaks = QtWidgets.QCheckBox(self.tab)
        self.checkBox_peaks.setGeometry(QtCore.QRect(160, 40, 171, 21))
        self.checkBox_peaks.setChecked(True)
        self.checkBox_peaks.setObjectName("checkBox_peaks")
        self.checkBox_modelRes = QtWidgets.QCheckBox(self.tab)
        self.checkBox_modelRes.setGeometry(QtCore.QRect(160, 70, 221, 21))
        self.checkBox_modelRes.setChecked(True)
        self.checkBox_modelRes.setObjectName("checkBox_modelRes")
        self.checkBox_corners = QtWidgets.QCheckBox(self.tab)
        self.checkBox_corners.setGeometry(QtCore.QRect(360, 40, 161, 21))
        self.checkBox_corners.setChecked(True)
        self.checkBox_corners.setObjectName("checkBox_corners")
        self.checkBox_grid = QtWidgets.QCheckBox(self.tab)
        self.checkBox_grid.setGeometry(QtCore.QRect(360, 10, 171, 21))
        self.checkBox_grid.setChecked(True)
        self.checkBox_grid.setObjectName("checkBox_grid")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 491, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_GPUfunc = QtWidgets.QGridLayout(
            self.gridLayoutWidget_2)
        self.gridLayout_GPUfunc.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_GPUfunc.setObjectName("gridLayout_GPUfunc")
        self.label_epsGrid = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsGrid.setObjectName("label_epsGrid")
        self.gridLayout_GPUfunc.addWidget(self.label_epsGrid, 2, 0, 1, 1)
        self.lineEdit_decGrid = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decGrid.setObjectName("lineEdit_decGrid")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decGrid, 2, 2, 1, 1)
        self.lineEdit_epsGrid = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsGrid.setObjectName("lineEdit_epsGrid")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsGrid, 2, 1, 1, 1)
        self.lineEdit_epsIntersect = QtWidgets.QLineEdit(
            self.gridLayoutWidget_2)
        self.lineEdit_epsIntersect.setObjectName("lineEdit_epsIntersect")
        self.gridLayout_GPUfunc.addWidget(
            self.lineEdit_epsIntersect, 1, 1, 1, 1)
        self.lineEdit_decIntersect = QtWidgets.QLineEdit(
            self.gridLayoutWidget_2)
        self.lineEdit_decIntersect.setObjectName("lineEdit_decIntersect")
        self.gridLayout_GPUfunc.addWidget(
            self.lineEdit_decIntersect, 1, 2, 1, 1)
        self.label_epsIntersect = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsIntersect.setObjectName("label_epsIntersect")
        self.gridLayout_GPUfunc.addWidget(self.label_epsIntersect, 1, 0, 1, 1)
        self.label_Rounding = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Rounding.setObjectName("label_Rounding")
        self.gridLayout_GPUfunc.addWidget(self.label_Rounding, 0, 2, 1, 1)
        self.label_eps = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_eps.setObjectName("label_eps")
        self.gridLayout_GPUfunc.addWidget(self.label_eps, 0, 1, 1, 1)
        self.label_epsModel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsModel.setObjectName("label_epsModel")
        self.gridLayout_GPUfunc.addWidget(self.label_epsModel, 4, 0, 1, 1)
        self.label_epsMerge = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_epsMerge.setObjectName("label_epsMerge")
        self.gridLayout_GPUfunc.addWidget(self.label_epsMerge, 6, 0, 1, 1)
        self.lineEdit_epsModel = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsModel.setObjectName("lineEdit_epsModel")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsModel, 4, 1, 1, 1)
        self.lineEdit_decModel = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decModel.setObjectName("lineEdit_decModel")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decModel, 4, 2, 1, 1)
        self.lineEdit_epsMerge = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_epsMerge.setObjectName("lineEdit_epsMerge")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_epsMerge, 6, 1, 1, 1)
        self.lineEdit_decMerge = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_decMerge.setObjectName("lineEdit_decMerge")
        self.gridLayout_GPUfunc.addWidget(self.lineEdit_decMerge, 6, 2, 1, 1)
        self.label_GPUTolerance = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_GPUTolerance.setObjectName("label_GPUTolerance")
        self.gridLayout_GPUfunc.addWidget(self.label_GPUTolerance, 0, 0, 1, 1)
        self.lineEdit_epsModeltArea = QtWidgets.QLineEdit(
            self.gridLayoutWidget_2)
        self.lineEdit_epsModeltArea.setStatusTip("")
        self.lineEdit_epsModeltArea.setObjectName("lineEdit_epsModeltArea")
        self.gridLayout_GPUfunc.addWidget(
            self.lineEdit_epsModeltArea, 5, 1, 1, 1)
        self.label_GPUtArea = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_GPUtArea.setObjectName("label_GPUtArea")
        self.gridLayout_GPUfunc.addWidget(self.label_GPUtArea, 5, 0, 1, 1)
        self.frame_growth_direction = QtWidgets.QFrame(self.tab)
        self.frame_growth_direction.setGeometry(
            QtCore.QRect(10, 330, 641, 131))
        self.frame_growth_direction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_growth_direction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_growth_direction.setObjectName("frame_growth_direction")
        self.label_growth_direction = QtWidgets.QLabel(
            self.frame_growth_direction)
        self.label_growth_direction.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_growth_direction.setObjectName("label_growth_direction")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(
            self.frame_growth_direction)
        self.horizontalLayoutWidget_2.setGeometry(
            QtCore.QRect(10, 30, 621, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_growth_direction = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_2)
        self.horizontalLayout_growth_direction.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_growth_direction.setObjectName(
            "horizontalLayout_growth_direction")
        self.radioButton_linearrule = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_2)
        self.radioButton_linearrule.setChecked(True)
        self.radioButton_linearrule.setObjectName("radioButton_linearrule")
        self.horizontalLayout_growth_direction.addWidget(
            self.radioButton_linearrule)
        self.radioButton_cosinerule = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_2)
        self.radioButton_cosinerule.setChecked(False)
        self.radioButton_cosinerule.setObjectName("radioButton_cosinerule")
        self.horizontalLayout_growth_direction.addWidget(
            self.radioButton_cosinerule)
        self.radioButton_tangentrule = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_2)
        self.radioButton_tangentrule.setObjectName("radioButton_tangentrule")
        self.horizontalLayout_growth_direction.addWidget(
            self.radioButton_tangentrule)
        self.radioButton_costanrule = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_2)
        self.radioButton_costanrule.setObjectName("radioButton_costanrule")
        self.horizontalLayout_growth_direction.addWidget(
            self.radioButton_costanrule)
        self.label_growth_direction_2 = QtWidgets.QLabel(
            self.frame_growth_direction)
        self.label_growth_direction_2.setGeometry(
            QtCore.QRect(10, 70, 141, 16))
        self.label_growth_direction_2.setObjectName("label_growth_direction_2")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(
            self.frame_growth_direction)
        self.horizontalLayoutWidget_4.setGeometry(
            QtCore.QRect(10, 90, 621, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_growthangle_a = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_4)
        self.radioButton_growthangle_a.setChecked(True)
        self.radioButton_growthangle_a.setObjectName(
            "radioButton_growthangle_a")
        self.horizontalLayout_2.addWidget(self.radioButton_growthangle_a)
        self.radioButton_growthangle_t = QtWidgets.QRadioButton(
            self.horizontalLayoutWidget_4)
        self.radioButton_growthangle_t.setChecked(False)
        self.radioButton_growthangle_t.setObjectName(
            "radioButton_growthangle_t")
        self.horizontalLayout_2.addWidget(self.radioButton_growthangle_t)
        self.frame_growth_rate = QtWidgets.QFrame(self.tab)
        self.frame_growth_rate.setGeometry(QtCore.QRect(10, 470, 301, 61))
        self.frame_growth_rate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_growth_rate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_growth_rate.setObjectName("frame_growth_rate")
        self.label_growth_rate = QtWidgets.QLabel(self.frame_growth_rate)
        self.label_growth_rate.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_growth_rate.setObjectName("label_growth_rate")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(
            self.frame_growth_rate)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 30, 281, 33))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_growth_rate = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget_3)
        self.horizontalLayout_growth_rate.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_growth_rate.setObjectName(
            "horizontalLayout_growth_rate")
        self.label_direction_depend = QtWidgets.QLabel(
            self.horizontalLayoutWidget_3)
        self.label_direction_depend.setObjectName("label_direction_depend")
        self.horizontalLayout_growth_rate.addWidget(
            self.label_direction_depend)
        self.lineEdit_growth_rate_Xi = QtWidgets.QLineEdit(
            self.horizontalLayoutWidget_3)
        self.lineEdit_growth_rate_Xi.setObjectName("lineEdit_growth_rate_Xi")
        self.horizontalLayout_growth_rate.addWidget(
            self.lineEdit_growth_rate_Xi)
        self.tabWidget_Main.addTab(self.tab, "")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(360, 710, 231, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(
            QtCore.QRect(600, 710, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setAutoRepeatInterval(100)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Pause = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Pause.setFont(font)
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.horizontalLayout.addWidget(self.pushButton_Pause)
        self.pushButton_Quit = QtWidgets.QPushButton(
            self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Quit.setFont(font)
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.horizontalLayout.addWidget(self.pushButton_Quit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuMenu.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(
            self.lineEdit_Model_Resolution, self.lineEdit_Evaporation_Rate)
        MainWindow.setTabOrder(
            self.lineEdit_Evaporation_Rate, self.lineEdit_Evaporation_Time)
        MainWindow.setTabOrder(
            self.lineEdit_Evaporation_Time, self.lineEdit_Grid_Space)
        MainWindow.setTabOrder(self.lineEdit_Grid_Space,
                               self.lineEdit_Raycast_Length)
        MainWindow.setTabOrder(
            self.lineEdit_Raycast_Length, self.lineEdit_Model_Limit)
        MainWindow.setTabOrder(self.lineEdit_Model_Limit,
                               self.pushButton_Load_Model)
        MainWindow.setTabOrder(self.pushButton_Load_Model,
                               self.pushButton_Load_Evap_Profile)
        MainWindow.setTabOrder(
            self.pushButton_Load_Evap_Profile, self.pushButton_Save_Evap_Profile)
        MainWindow.setTabOrder(
            self.pushButton_Save_Evap_Profile, self.pushButton_Abort_Run)
        MainWindow.setTabOrder(self.pushButton_Abort_Run,
                               self.pushButton_Clear_Run)
        MainWindow.setTabOrder(self.pushButton_Clear_Run,
                               self.pushButton_Reset_Graph)
        MainWindow.setTabOrder(
            self.pushButton_Reset_Graph, self.tabWidget_Main)
        MainWindow.setTabOrder(self.tabWidget_Main, self.graphicsView_Model)
        MainWindow.setTabOrder(self.graphicsView_Model,
                               self.graphicsView_Evap_Profile_Top)
        MainWindow.setTabOrder(
            self.graphicsView_Evap_Profile_Top, self.graphicsView_Evap_Profile_Bottom)
        MainWindow.setTabOrder(
            self.graphicsView_Evap_Profile_Bottom, self.textBrowser_Log)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Physical Vapor Depostion Simulator"))
        self.label_Model_Resolution.setText(
            _translate("MainWindow", "Model Resolution"))
        self.label_Grid_Space.setText(_translate("MainWindow", "Grid Space"))
        self.label_Evaporation_Rate.setText(
            _translate("MainWindow", "Evaporation Rate"))
        self.label_Raycast_Length.setText(
            _translate("MainWindow", "Raycast Length"))
        self.label_Evaporation_Time.setText(
            _translate("MainWindow", "Evaporation Time"))
        self.label_Model_Resolution_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Model_Limit.setText(_translate("MainWindow", "Model Limit"))
        self.label_Evaporation_Rate_Unit.setText(
            _translate("MainWindow", "Å/s"))
        self.label_Evaporation_Time_Unit.setText(_translate("MainWindow", "s"))
        self.label_Grid_Space_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Raycast_Length_Unit.setText(_translate("MainWindow", "Å"))
        self.label_Model_Limit_Unit.setText(_translate("MainWindow", "Pts"))
        self.pushButton_Load_Model.setText(
            _translate("MainWindow", "Load Model"))
        self.pushButton_Load_Evap_Profile.setText(
            _translate("MainWindow", "Load Evap Profile"))
        self.pushButton_load_settings.setText(
            _translate("MainWindow", "Load Settings"))
        self.pushButton_Save_Evap_Profile.setText(
            _translate("MainWindow", "Save Evap Model"))
        self.pushButton_Abort_Run.setText(
            _translate("MainWindow", "Abort Run"))
        self.pushButton_Clear_Run.setText(
            _translate("MainWindow", "Clear Run"))
        self.pushButton_Reset_Graph.setText(
            _translate("MainWindow", "Reset Graph"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_1), _translate("MainWindow", "Model"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_2), _translate("MainWindow", "Evap Profile"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab_3), _translate("MainWindow", "Log"))
        self.label_GPU_Corrections.setText(
            _translate("MainWindow", "GPU Corrections:"))
        self.label_CPU_Corrections.setText(
            _translate("MainWindow", "CPU Corrections:"))
        self.checkBox_divet.setText(_translate(
            "MainWindow", "Average out divets"))
        self.checkBox_peaks.setText(_translate(
            "MainWindow", "Average out peaks"))
        self.checkBox_modelRes.setText(
            _translate("MainWindow", "Enforce Model Limit"))
        self.checkBox_corners.setText(
            _translate("MainWindow", "Preserve corners"))
        self.checkBox_grid.setText(_translate(
            "MainWindow", "Enforce Grid Space"))
        self.label_epsGrid.setText(_translate("MainWindow", "Grid"))
        self.lineEdit_decGrid.setText(_translate("MainWindow", "10"))
        self.lineEdit_epsGrid.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_epsIntersect.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_decIntersect.setText(_translate("MainWindow", "10"))
        self.label_epsIntersect.setText(
            _translate("MainWindow", "Intersection"))
        self.label_Rounding.setText(_translate(
            "MainWindow", "Rounding Accuracy"))
        self.label_eps.setText(_translate(
            "MainWindow", "Computer Determined Zero"))
        self.label_epsModel.setText(_translate("MainWindow", "Model"))
        self.label_epsMerge.setText(_translate("MainWindow", "Merge"))
        self.lineEdit_epsModel.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_decModel.setText(_translate("MainWindow", "10"))
        self.lineEdit_epsMerge.setText(_translate("MainWindow", "1e-16"))
        self.lineEdit_decMerge.setText(_translate("MainWindow", "10"))
        self.label_GPUTolerance.setText(_translate("MainWindow", "GPU func:"))
        self.lineEdit_epsModeltArea.setText(_translate("MainWindow", "1e-10"))
        self.label_GPUtArea.setText(_translate("MainWindow", "Model tArea"))
        self.label_growth_direction.setText(
            _translate("MainWindow", "Growth Direction"))
        self.radioButton_linearrule.setText(_translate("MainWindow", "Linear"))
        self.radioButton_cosinerule.setText(
            _translate("MainWindow", "Cosine Rule"))
        self.radioButton_tangentrule.setText(
            _translate("MainWindow", "Tangent Rule"))
        self.radioButton_costanrule.setText(
            _translate("MainWindow", "Cos+Tan Rule"))
        self.label_growth_direction_2.setText(
            _translate("MainWindow", "Growth Angle"))
        self.radioButton_growthangle_a.setText(
            _translate("MainWindow", "β = fn(α)"))
        self.radioButton_growthangle_t.setText(
            _translate("MainWindow", "β = fn(θ)"))
        self.label_growth_rate.setText(_translate("MainWindow", "Growth Rate"))
        self.label_direction_depend.setText(
            _translate("MainWindow", "Directional Dependence"))
        self.lineEdit_growth_rate_Xi.setText(_translate("MainWindow", "0"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(
            self.tab), _translate("MainWindow", "Settings"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_Quit.setText(_translate("MainWindow", "Quit"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


class Ui_Dialog_HelpTree(object):
    def setupUi(self, Dialog_HelpTree):
        Dialog_HelpTree.setObjectName("Dialog_HelpTree")
        Dialog_HelpTree.resize(733, 461)
        self.treeWidget_Help = QtWidgets.QTreeWidget(Dialog_HelpTree)
        self.treeWidget_Help.setGeometry(QtCore.QRect(10, 10, 711, 441))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(
            self.treeWidget_Help.sizePolicy().hasHeightForWidth())
        self.treeWidget_Help.setSizePolicy(sizePolicy)
        self.treeWidget_Help.setTabKeyNavigation(True)
        self.treeWidget_Help.setAlternatingRowColors(False)
        self.treeWidget_Help.setAnimated(True)
        self.treeWidget_Help.setAllColumnsShowFocus(False)
        self.treeWidget_Help.setWordWrap(True)
        self.treeWidget_Help.setObjectName("treeWidget_Help")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Help)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Help)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Help)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Help)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)

        self.retranslateUi(Dialog_HelpTree)
        QtCore.QMetaObject.connectSlotsByName(Dialog_HelpTree)

    def retranslateUi(self, Dialog_HelpTree):
        _translate = QtCore.QCoreApplication.translate
        Dialog_HelpTree.setWindowTitle(_translate("Dialog_HelpTree", "Dialog"))
        self.treeWidget_Help.setSortingEnabled(False)
        self.treeWidget_Help.headerItem().setText(
            0, _translate("Dialog_HelpTree", "Contents"))
        self.treeWidget_Help.headerItem().setText(
            1, _translate("Dialog_HelpTree", "Description"))
        __sortingEnabled = self.treeWidget_Help.isSortingEnabled()
        self.treeWidget_Help.setSortingEnabled(False)
        self.treeWidget_Help.topLevelItem(0).setText(
            0, _translate("Dialog_HelpTree", "Ray Cast Method"))
        self.treeWidget_Help.topLevelItem(0).setText(1, _translate("Dialog_HelpTree", "The model is treated as a series of vertices. Each vertice has a ray casted from it to\n"
                                                                   "determine potential intersections. The results of this intersection test determine\n"
                                                                   "shadowing and material growth."))
        self.treeWidget_Help.topLevelItem(0).child(0).setText(
            0, _translate("Dialog_HelpTree", "Corner Handling"))
        self.treeWidget_Help.topLevelItem(0).child(0).setText(1, _translate("Dialog_HelpTree", "Pi[i - 1] != 0 and Pi[i + 1] == 0 or Pi[i + 1] != 0 and Pi[i - 1] == 0:\n"
                                                                            "The ith point may be kept along with the adjusted ith point"))
        self.treeWidget_Help.topLevelItem(0).child(1).setText(
            0, _translate("Dialog_HelpTree", "Defect Handling"))
        self.treeWidget_Help.topLevelItem(0).child(1).setText(1, _translate(
            "Dialog_HelpTree", "RC solution doesn\'t exist. Either average or drop the point."))
        self.treeWidget_Help.topLevelItem(0).child(1).child(
            0).setText(0, _translate("Dialog_HelpTree", "Peaks"))
        self.treeWidget_Help.topLevelItem(0).child(1).child(0).setText(1, _translate("Dialog_HelpTree", " if Pi[i - 1] != 0 and Pi[i] == 0 and Pi[i + 1] != 0:\n"
                                                                                     "The ith point is averaged against its neighbors."))
        self.treeWidget_Help.topLevelItem(0).child(1).child(
            1).setText(0, _translate("Dialog_HelpTree", "Divets"))
        self.treeWidget_Help.topLevelItem(0).child(1).child(1).setText(1, _translate("Dialog_HelpTree", "if Pi[i - 1] == 0 and Pi[i] != 0 and Pi[i + 1] == 0:\n"
                                                                                     "The ith point is averaged against its neighbors."))
        self.treeWidget_Help.topLevelItem(0).child(2).setText(
            0, _translate("Dialog_HelpTree", "Evaporation Rate"))
        self.treeWidget_Help.topLevelItem(0).child(2).setText(1, _translate(
            "Dialog_HelpTree", "Crystal thickness monitor adjusted evaporation rate"))
        self.treeWidget_Help.topLevelItem(0).child(3).setText(
            0, _translate("Dialog_HelpTree", "Evaporation Time"))
        self.treeWidget_Help.topLevelItem(0).child(3).setText(1, _translate(
            "Dialog_HelpTree", "Total length of evaporation in seconds"))
        self.treeWidget_Help.topLevelItem(0).child(4).setText(
            0, _translate("Dialog_HelpTree", "Grid Space"))
        self.treeWidget_Help.topLevelItem(0).child(4).setText(1, _translate("Dialog_HelpTree", "Vertice resolution. Model attempts to merge points within a distance smaller than this.\n"
                                                                            "Helps reduce artifacts from forming."))
        self.treeWidget_Help.topLevelItem(0).child(5).setText(
            0, _translate("Dialog_HelpTree", "Model Limit"))
        self.treeWidget_Help.topLevelItem(0).child(5).setText(1, _translate("Dialog_HelpTree", "Maximum amount of vertices allowed before applying a reduce function to\n"
                                                                            "cut down on the number of vertices in the model."))
        self.treeWidget_Help.topLevelItem(0).child(6).setText(
            0, _translate("Dialog_HelpTree", "Model Resolution"))
        self.treeWidget_Help.topLevelItem(0).child(6).setText(1, _translate(
            "Dialog_HelpTree", "Initial spacing of vertices when model is loaded into memory."))
        self.treeWidget_Help.topLevelItem(0).child(7).setText(
            0, _translate("Dialog_HelpTree", "Raycast Length"))
        self.treeWidget_Help.topLevelItem(0).child(7).setText(1, _translate("Dialog_HelpTree", "Length of the casted ray per vertice. May be adjusted down to only check shadowing of\n"
                                                                            "nearest neighbors."))
        self.treeWidget_Help.topLevelItem(1).setText(
            0, _translate("Dialog_HelpTree", "Growth Rate"))
        self.treeWidget_Help.topLevelItem(1).setText(1, _translate("Dialog_HelpTree", "Φ = Evaporation flux\n"
                                                                   "Ξ = Directional dependence"))
        self.treeWidget_Help.topLevelItem(1).child(0).setText(
            0, _translate("Dialog_HelpTree", "Cosine Rule"))
        self.treeWidget_Help.topLevelItem(1).child(0).setText(
            1, _translate("Dialog_HelpTree", "rate = Φ * exp(Ξ) * cos(α)"))
        self.treeWidget_Help.topLevelItem(2).setText(
            0, _translate("Dialog_HelpTree", "Growth Direction"))
        self.treeWidget_Help.topLevelItem(2).setText(1, _translate("Dialog_HelpTree", "α = Evaporation angle with respect to surface normal\n"
                                                                   "β = Growth direction with respect to surface normal"))
        self.treeWidget_Help.topLevelItem(2).child(0).setText(
            0, _translate("Dialog_HelpTree", "Linear"))
        self.treeWidget_Help.topLevelItem(2).child(0).setText(
            1, _translate("Dialog_HelpTree", "β = α"))
        self.treeWidget_Help.topLevelItem(2).child(1).setText(
            0, _translate("Dialog_HelpTree", "Cosine Rule"))
        self.treeWidget_Help.topLevelItem(2).child(1).setText(
            1, _translate("Dialog_HelpTree", "β = α - arcsin((1 - cos(α)) / 2)"))
        self.treeWidget_Help.topLevelItem(2).child(2).setText(
            0, _translate("Dialog_HelpTree", "Tangent Rule"))
        self.treeWidget_Help.topLevelItem(2).child(2).setText(
            1, _translate("Dialog_HelpTree", "β = arctan(tan(α) / 2)  "))
        self.treeWidget_Help.topLevelItem(3).setText(
            0, _translate("Dialog_HelpTree", "Ballistic Method"))
        self.treeWidget_Help.topLevelItem(3).child(0).setText(
            0, _translate("Dialog_HelpTree", "Not Implemented"))
        self.treeWidget_Help.topLevelItem(3).child(0).setText(1, _translate(
            "Dialog_HelpTree", "To be ray march of ballistic method in GPU"))
        self.treeWidget_Help.setSortingEnabled(__sortingEnabled)
